# DECISION TREE (LACE)

In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# These are the plotting modules adn libraries we'll use:
import matplotlib as mpl
import seaborn as sns

# The normal imports
from numpy.random import randn

# Import the stats librayr from numpy
from scipy import stats
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB #SciKitLearn GaussianNB Naive Bayes import
from sklearn import tree ##SciKitLearn GaussianNB Naive Bayes import


# Command so that plots appear in the iPython Notebook
%matplotlib inline

train = pd.read_csv('SumStudentClicksxResult-2-0-50.csv')   # better be in the correct directory!
test = pd.read_csv('SumStudentClicksxResult-2-50-100.csv')
test.head(5)

id_student  SumOfsum_click final_result
0      100893             250         Pass
1      101781             891         Pass
2      102806             486         Pass
3      102952             242         Pass
4     1035023             496         Pass

In [2]:
train.head(5)

id_student  SumOfsum_click final_result
0      100893             206         Pass
1      101781            1505         Pass
2      102806             590         Pass
3      102952             444         Pass
4     1035023             459         Pass

In [3]:
cols = ['SumOfsum_click']
cols2 = ['final_result']

trainArr = train[cols].to_numpy()
trainRes = train[cols2].to_numpy()

testArr = test[cols].to_numpy()
testRes = test[cols2].to_numpy()

#depreciated transformation to numpy array
# trainArr = train.to_numpy(cols)
# trainRes = train.to_numpy(cols2)

# testArr = test.to_numpy(cols)
# testRes = test.to_numpy(cols2)

#clf = GaussianNB()
clf = tree.DecisionTreeClassifier()

# print(trainArr[0])
# print(trainRes[0])
# print(testArr[0])
# print(testRes[0])

output = clf.fit(trainArr, trainRes).predict(testArr)

for i in range(390):
    #if testRes[i][0] == output[i] and testRes[i]=="Distinction":
    #if testRes[i][0] == output[i] and testRes[i]<>"Pass":
    if testRes[i][0] == output[i]:
        print('CORRECT   ' + str(output[i]) + "   " + str(testRes[i]))
        #print("PREDICTION:  " + str(output[i]) + "  " + str(testArr[i]) + "  " + str(testRes[i]) + "     RIGHT")
    else:
        print('INCORRECT ' + str(output[i]) + "   " + str(testRes[i]))
        #print("PREDICTION:  " + str(output[i]) + "  " + str(testArr[i]) + "  " + str(testRes[i]) + "     WRONG")

INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Withdrawn   ['Withdrawn']
CORRECT   Pass   ['Pass']
INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Withdrawn   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Withdrawn   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Fail   ['Pass']
INCORRECT Distinction   ['Pass']
INCORRECT Pass   ['Withdrawn']
INCORRECT Fail   ['Pass']
INCORRECT Pass   ['Distinction']
INCORRECT Fail   ['Pass']
INCORRECT Fail   ['Withdrawn']
INCORRECT Fail   ['Pass']
INCORRECT Fail   ['Withdrawn']
INCORRECT Distinction   ['Pass']
CORRECT   Fail   ['Fail']
INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Pass   ['Withdrawn']
INCORRECT Pass   ['Fail']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INC

In [4]:
correct = 0.0

for i in range(len(output)): 
    if testRes[i][0] == output[i]: 
        correct += 1
    
print(correct / len(output))


#print("Accuracy: " + gnb.score(testArr, testRes))
print("Accuracy: " + str(clf.score(testArr, testRes)))

0.5370843989769821
Accuracy: 0.5370843989769821


In [5]:
expected = testRes
predicted = clf.predict(testArr)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

 Distinction       0.11      0.10      0.10        21
        Fail       0.21      0.32      0.25        50
        Pass       0.71      0.69      0.70       275
   Withdrawn       0.07      0.04      0.05        45

    accuracy                           0.54       391
   macro avg       0.27      0.29      0.28       391
weighted avg       0.54      0.54      0.54       391

[[  2   2  16   1]
 [  0  16  31   3]
 [ 15  48 190  22]
 [  1  11  31   2]]


In [6]:
count=0 
passn=0
fail=0
distinction=0
withdrawn=0
for i in range(len(output)): 
    count += 1
    if testRes[i][0]=='Pass':
        passn += 1
    if testRes[i][0]=='Fail':
        fail += 1
    if testRes[i][0]=='Distinction':
        distinction += 1
    if testRes[i][0]=='Withdrawn':
        withdrawn += 1
print ("Pass: " + str(passn))
print ("Fail: " + str(fail))
print ("Distinction: " + str(distinction))
print ("Withdrawn: " + str(withdrawn))
    

Pass: 275
Fail: 50
Distinction: 21
Withdrawn: 45


# OUR VERSION OF THE DATASET

In [16]:
vle = pd.read_csv('studentVle.csv')
info = pd.read_csv('studentInfo.csv')

In [17]:
import csv
import operator
import random

TRAIN_SET_PERCENTAGE = 0.4

STUDENT_INFO = 'studentInfo.csv'
TRAIN_STUDENT_INFO = 'studentInfoTrain.csv'
TEST_STUDENT_INFO = 'studentInfoTest.csv'

STUDENT_VLE = 'studentVle.csv'
TRAIN_STUDENT_VLE = 'studentVleTrain.csv'
TEST_STUDENT_VLE = 'studentVleTest.csv'

if __name__ == '__main__':
    # GET ALL STUDENT IDS
    student_ids = list()

    with open(STUDENT_INFO) as student_info:
        student_info_reader = csv.reader(student_info, delimiter=',', quotechar='"')

        for row in student_info_reader:
            if student_info_reader.line_num == 1:
                continue

            student_ids.append(row[2])

    # SPLIT STUDENT IDS INTO TRAINING AND TEST
    length = len(student_ids)
    train_length = round(length * TRAIN_SET_PERCENTAGE)

    train_indexes = random.sample(range(0, length - 1), train_length)
    train_student_ids = set(operator.itemgetter(*train_indexes)(student_ids))
    test_student_ids = set(student_ids).difference(set(train_student_ids))

    # CREATE NEW DATASETS
    for [TRAIN_FILE, TEST_FILE, STUDENT_FILE] in [[TRAIN_STUDENT_INFO, TEST_STUDENT_INFO, STUDENT_INFO],
                                                  [TRAIN_STUDENT_VLE, TEST_STUDENT_VLE, STUDENT_VLE]]:
        with open(TRAIN_FILE, 'w', newline='') as train_file, open(TEST_FILE, 'w', newline='') as test_file, open(
                STUDENT_FILE) as student_info:
            student_info_reader = csv.reader(student_info, delimiter=',', quotechar='"')
            train_file_writer = csv.writer(train_file)
            test_file_writer = csv.writer(test_file)

            for row in student_info_reader:
                if student_info_reader.line_num == 1:
                    train_file_writer.writerow(row)
                    test_file_writer.writerow(row)
                    continue

                student_id = row[2]

                if student_id in train_student_ids:
                    train_file_writer.writerow(row)
                else:
                    test_file_writer.writerow(row)


In [93]:
vle_train = pd.read_csv('studentVleTrain.csv')
vle_test = pd.read_csv('studentVleTest.csv')

info_train = pd.read_csv('studentInfoTrain.csv')
info_test = pd.read_csv('studentInfoTest.csv')

In [73]:
vle_train.head(5)
info_train.head(5)

code_module code_presentation  id_student gender                region  \
0         AAA             2013J       11391      M   East Anglian Region   
1         AAA             2013J       32885      F  West Midlands Region   
2         AAA             2013J       38053      M                 Wales   
3         AAA             2013J       45462      M              Scotland   
4         AAA             2013J       57506      M          South Region   

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                     0   
1     Lower Than A Level   50-60%     0-35                     0   
2  A Level or Equivalent   80-90%    35-55                     0   
3       HE Qualification   30-40%     0-35                     0   
4     Lower Than A Level   70-80%    35-55                     0   

   studied_credits disability final_result  
0              240          N         Pass  
1               60          N         Pass  
2               60          N         Pass  
3               60          N         Pass  
4               60          N         Pass

In [114]:
#for now, select only course AAA and 2013
vle_train_a = vle_train.loc[(vle_train.code_module == 'AAA') & (vle_train.code_presentation == '2013J')]
vle_test_a = vle_test.loc[(vle_test.code_module == 'AAA') & (vle_test.code_presentation == '2013J')]

#reduce vle set to only include relevant columns
vle_train_a = vle_train_a[['id_student', 'date', 'sum_click']]
vle_test_a = vle_test_a[['id_student', 'date', 'sum_click']]

#group vle data on student id and date, while summing the clicks
vle_train_group = vle_train_a.groupby(['id_student', 'date']).agg({'sum_click':'sum'}).reset_index()
vle_test_group = vle_test_a.groupby(['id_student', 'date']).agg({'sum_click':'sum'}).reset_index()

#reduce train set to only include relevant columns
# train = train[['id_student', 'final_result']]
# train_short = train.drop_duplicates(subset = ["id_student"])

#for now, select only course AAA and 2013 of demo info
info_train_a = info_train.loc[(info_train.code_module == 'AAA') & (info_train.code_presentation == '2013J')]
info_test_a = info_test.loc[(info_test.code_module == 'AAA') & (info_test.code_presentation == '2013J')]

#reduce info set to only include relevant columns
info_train_a = info_train_a[['id_student', 'gender', 'highest_education', 'num_of_prev_attempts', 'final_result']]
info_test_a = info_test_a[['id_student', 'gender', 'highest_education', 'num_of_prev_attempts', 'final_result']]

#change num_of_prev_attempts to boolean, need to only run this once
info_train_a.loc[info_train_a['num_of_prev_attempts'] > 0, ['num_of_prev_attempts']] = 'y'      
info_train_a.loc[info_train_a['num_of_prev_attempts'] == 0, ['num_of_prev_attempts']] = 'n'

info_train_a = info_train_a.rename(columns={"num_of_prev_attempts": "continued"})
                        
info_test_a.loc[info_test_a['num_of_prev_attempts'] > 0, ['num_of_prev_attempts']] = 'y'      
info_test_a.loc[info_test_a['num_of_prev_attempts'] == 0, ['num_of_prev_attempts']] = 'n'

info_test_a = info_test_a.rename(columns={"num_of_prev_attempts": "continued"})

# info_a.loc[info_a['continued'] == 'y']
# info_a.loc[info_a['continued'] == 'n'] 

#merge (left join) two dataframes on student id
vle_info_train = pd.merge(vle_train_group, info_train_a, on = 'id_student')
vle_info_test = pd.merge(vle_test_group, info_test_a, on = 'id_student')
                        
#merge (left join) student results on student id
# all_train = pd.merge(vle_info_train, train_short, on = 'id_student')
# all_test = pd.merge(vle_info_test, train_short, on = 'id_student')

In [115]:
c = all_train.columns.difference(['id_student','date','gender','highest_education','continued','final_result'])
all_train[c] = all_train[c].cumsum()
all_train

id_student  date      sum_click gender   highest_education continued  \
0           11391    -5             98      M    HE Qualification         n   
1           11391     0            343      M    HE Qualification         n   
2           11391     1            862      M    HE Qualification         n   
3           11391     2           1659      M    HE Qualification         n   
4           11391     6           2737      M    HE Qualification         n   
...           ...   ...            ...    ...                 ...       ...   
14894     2698257   228  9768630861984      M  Lower Than A Level         n   
14895     2698257   233  9770632164544      M  Lower Than A Level         n   
14896     2698257   234  9772633740349      M  Lower Than A Level         n   
14897     2698257   235  9774635589407      M  Lower Than A Level         n   
14898     2698257   268  9776637711719      M  Lower Than A Level         n   

      final_result  
0             Pass  
1             Pass  
2             Pass  
3             Pass  
4             Pass  
...            ...  
14894         Pass  
14895         Pass  
14896         Pass  
14897         Pass  
14898         Pass  

[14899 rows x 7 columns]

In [116]:
print(all_train.min())
print(all_test.min())

id_student                           11391
date                                   -10
sum_click                               98
gender                                   F
highest_education    A Level or Equivalent
continued                                n
final_result                   Distinction
dtype: object
id_student                           28400
date                                   -10
sum_click                                1
gender                                   F
highest_education    A Level or Equivalent
continued                                n
final_result                   Distinction
dtype: object


In [117]:
all_train.to_csv(r'studentTrainAll.csv', index = False)
all_test.to_csv(r'studentTestAll.csv', index = False)

In [118]:
all_train.head(10)

id_student  date  sum_click gender highest_education continued final_result
0       11391    -5         98      M  HE Qualification         n         Pass
1       11391     0        343      M  HE Qualification         n         Pass
2       11391     1        862      M  HE Qualification         n         Pass
3       11391     2       1659      M  HE Qualification         n         Pass
4       11391     6       2737      M  HE Qualification         n         Pass
5       11391     9       4116      M  HE Qualification         n         Pass
6       11391    17       5847      M  HE Qualification         n         Pass
7       11391    18       7979      M  HE Qualification         n         Pass
8       11391    29      10530      M  HE Qualification         n         Pass
9       11391    30      13505      M  HE Qualification         n         Pass

In [119]:
all_test.head(10)

id_student  date  sum_click gender highest_education continued final_result
0       28400   -10         70      F  HE Qualification         n         Pass
1       28400    -8          9      F  HE Qualification         n         Pass
2       28400    -7         81      F  HE Qualification         n         Pass
3       28400    -6         13      F  HE Qualification         n         Pass
4       28400    -5          4      F  HE Qualification         n         Pass
5       28400    -4          6      F  HE Qualification         n         Pass
6       28400    -2         32      F  HE Qualification         n         Pass
7       28400     0         48      F  HE Qualification         n         Pass
8       28400     1         16      F  HE Qualification         n         Pass
9       28400     4         29      F  HE Qualification         n         Pass

In [122]:
#list and number of unique students in course AAA (*train)
unique = all_train['id_student'].unique()
print(all_train['id_student'].nunique())

#list and number of unique students in course AAA (*test)
unique = all_test['id_student'].unique()
print(all_test['id_student'].nunique())

173
204


# METRICS (LACE)

In [14]:
feature_names=('Pass','Fail', 'Distinction', 'Withdrawn')
with open("studentTree.dot", 'w') as f:
         f = tree.export_graphviz(clf, out_file=f, feature_names=feature_names)

ValueError: Length of feature_names, 4 does not match number of features, 1

In [ ]:
plt.hist(testArr)

In [ ]:
plt.hist(testArr, density=True,color='indianred',alpha=0.5,bins=20)
#plt.hist(output, normed=True,alpha=0.5,bins=20)

In [ ]:
sns.distplot(testArr,bins=25,
            kde_kws={'color':'indianred','label':'KDE PLOT'},
            hist_kws={'color':'blue','label':"HIST"})

In [ ]:
plt.hist(testArr, density=True,color='indianred',alpha=0.5,bins=20)
plt.hist(trainArr, density=True,alpha=0.5,bins=20)

In [ ]:
sns.heatmap(testArr)