# DECISION TREE (LACE)

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# These are the plotting modules adn libraries we'll use:
import matplotlib as mpl
import seaborn as sns

# The normal imports
from numpy.random import randn

# Import the stats librayr from numpy
from scipy import stats
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB #SciKitLearn GaussianNB Naive Bayes import
from sklearn import tree ##SciKitLearn GaussianNB Naive Bayes import


# Command so that plots appear in the iPython Notebook
%matplotlib inline

train = pd.read_csv('SumStudentClicksxResult-2-0-50.csv')   # better be in the correct directory!
test = pd.read_csv('SumStudentClicksxResult-2-50-100.csv')
test.head(5)

id_student  SumOfsum_click final_result
0      100893             250         Pass
1      101781             891         Pass
2      102806             486         Pass
3      102952             242         Pass
4     1035023             496         Pass

In [21]:
train.head(5)

id_student  SumOfsum_click final_result
0      100893             206         Pass
1      101781            1505         Pass
2      102806             590         Pass
3      102952             444         Pass
4     1035023             459         Pass

In [22]:
cols = ['SumOfsum_click']
cols2 = ['final_result']

trainArr = train[cols].to_numpy()
trainRes = train[cols2].to_numpy()

testArr = test[cols].to_numpy()
testRes = test[cols2].to_numpy()

#depreciated transformation to numpy array
# trainArr = train.to_numpy(cols)
# trainRes = train.to_numpy(cols2)

# testArr = test.to_numpy(cols)
# testRes = test.to_numpy(cols2)

#clf = GaussianNB()
clf = tree.DecisionTreeClassifier()

# print(trainArr[0])
# print(trainRes[0])
# print(testArr[0])
# print(testRes[0])

output = clf.fit(trainArr, trainRes).predict(testArr)

for i in range(390):
    #if testRes[i][0] == output[i] and testRes[i]=="Distinction":
    #if testRes[i][0] == output[i] and testRes[i]<>"Pass":
    if testRes[i][0] == output[i]:
        print('CORRECT   ' + str(output[i]) + "   " + str(testRes[i]))
        #print("PREDICTION:  " + str(output[i]) + "  " + str(testArr[i]) + "  " + str(testRes[i]) + "     RIGHT")
    else:
        print('INCORRECT ' + str(output[i]) + "   " + str(testRes[i]))
        #print("PREDICTION:  " + str(output[i]) + "  " + str(testArr[i]) + "  " + str(testRes[i]) + "     WRONG")

INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Withdrawn   ['Withdrawn']
CORRECT   Pass   ['Pass']
INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Withdrawn   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Withdrawn   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Fail   ['Pass']
INCORRECT Distinction   ['Pass']
INCORRECT Pass   ['Withdrawn']
INCORRECT Fail   ['Pass']
INCORRECT Pass   ['Distinction']
INCORRECT Fail   ['Pass']
INCORRECT Fail   ['Withdrawn']
INCORRECT Fail   ['Pass']
INCORRECT Fail   ['Withdrawn']
INCORRECT Distinction   ['Pass']
CORRECT   Fail   ['Fail']
INCORRECT Fail   ['Pass']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INCORRECT Pass   ['Withdrawn']
INCORRECT Pass   ['Fail']
CORRECT   Pass   ['Pass']
CORRECT   Pass   ['Pass']
INC

In [23]:
correct = 0.0

for i in range(len(output)): 
    if testRes[i][0] == output[i]: 
        correct += 1
    
print(correct / len(output))


#print("Accuracy: " + gnb.score(testArr, testRes))
print("Accuracy: " + str(clf.score(testArr, testRes)))

0.5370843989769821
Accuracy: 0.5370843989769821


In [24]:
expected = testRes
predicted = clf.predict(testArr)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

 Distinction       0.11      0.10      0.10        21
        Fail       0.21      0.32      0.25        50
        Pass       0.71      0.69      0.70       275
   Withdrawn       0.07      0.04      0.05        45

    accuracy                           0.54       391
   macro avg       0.27      0.29      0.28       391
weighted avg       0.54      0.54      0.54       391

[[  2   2  16   1]
 [  0  16  31   3]
 [ 15  48 190  22]
 [  1  11  31   2]]


In [25]:
count=0 
passn=0
fail=0
distinction=0
withdrawn=0
for i in range(len(output)): 
    count += 1
    if testRes[i][0]=='Pass':
        passn += 1
    if testRes[i][0]=='Fail':
        fail += 1
    if testRes[i][0]=='Distinction':
        distinction += 1
    if testRes[i][0]=='Withdrawn':
        withdrawn += 1
print ("Pass: " + str(passn))
print ("Fail: " + str(fail))
print ("Distinction: " + str(distinction))
print ("Withdrawn: " + str(withdrawn))
    

Pass: 275
Fail: 50
Distinction: 21
Withdrawn: 45


# OUR VERSION OF THE DATASET

In [33]:
vle = pd.read_csv('studentVle.csv')
info = pd.read_csv('studentInfo.csv')

In [27]:
vle.head(5)

code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [38]:
#for now, select only course AAA
vle_a = vle[vle.code_module == 'AAA']

#reduce vle set to only include relevant columns
vle_a = vle_a[['id_student', 'date', 'sum_click']]

#group vle data on student id and date, while summing the clicks
vle_group = vle_a.groupby(['id_student', 'date']).agg({'sum_click':'sum'}).reset_index()

#reduce train set to only include relevant columns
train_short = train[['id_student', 'final_result']]

#for now, select only course AAA of demo info
info_a = info[info.code_module == 'AAA']

#reduce info set to only include relevant columns
info_a = info_a[['id_student', 'gender', 'highest_education', 'num_of_prev_attempts']]

#merge (left join) two dataframes on student id
vle_info = pd.merge(vle_group, info_a, on = 'id_student')

#merge (left join) student results on student id
vle_all = pd.merge(vle_info, train_short, on = 'id_student')

vle_all

id_student  date  sum_click gender   highest_education  \
0           11391    -5         98      M    HE Qualification   
1           11391     0         49      M    HE Qualification   
2           11391     1        127      M    HE Qualification   
3           11391     2          4      M    HE Qualification   
4           11391     6          3      M    HE Qualification   
...           ...   ...        ...    ...                 ...   
44499     2698257   228          8      M  Lower Than A Level   
44500     2698257   233          4      M  Lower Than A Level   
44501     2698257   234          9      M  Lower Than A Level   
44502     2698257   235          8      M  Lower Than A Level   
44503     2698257   268          1      M  Lower Than A Level   

       num_of_prev_attempts final_result  
0                         0         Pass  
1                         0         Pass  
2                         0         Pass  
3                         0         Pass  
4                         0         Pass  
...                     ...          ...  
44499                     0         Pass  
44500                     0         Pass  
44501                     0         Pass  
44502                     0         Pass  
44503                     0         Pass  

[44504 rows x 7 columns]

In [44]:
vle_all['id_student']

id_student
11391      1
28400      1
30268      1
31604      1
32885      1
          ..
2689958    1
2691206    1
2691244    1
2694424    1
2698257    1
Name: id_student, Length: 377, dtype: int64

In [29]:
train.head(1)

id_student  SumOfsum_click final_result
0      100893             206         Pass

In [30]:
test.head(1)

id_student  SumOfsum_click final_result
0      100893             250         Pass

In [31]:
#for seeing where they split their train and test sets
check = merged[merged.id_student == 100893]
check['sum_click'].sum()

744

In [32]:
check

id_student  date  sum_click final_result
2352      100893    -9         14         Pass
2353      100893    -2         13         Pass
2354      100893     3          2         Pass
2355      100893     4          9         Pass
2356      100893     5         21         Pass
2357      100893     6          5         Pass
2358      100893     8          3         Pass
2359      100893    13          2         Pass
2360      100893    16         39         Pass
2361      100893    17          9         Pass
2362      100893    20          1         Pass
2363      100893    25         10         Pass
2364      100893    27          5         Pass
2365      100893    28          1         Pass
2366      100893    31          9         Pass
2367      100893    32         23         Pass
2368      100893    33         20         Pass
2369      100893    34         20         Pass
2370      100893    37         67         Pass
2371      100893    44         10         Pass
2372      100893    45         34         Pass
2373      100893    46         21         Pass
2374      100893    50          4         Pass
2375      100893    72         13         Pass
2376      100893    74          8         Pass
2377      100893    75         12         Pass
2378      100893    76         13         Pass
2379      100893   100         10         Pass
2380      100893   111         26         Pass
2381      100893   114         14         Pass
2382      100893   115          3         Pass
2383      100893   116         15         Pass
2384      100893   135          1         Pass
2385      100893   145          4         Pass
2386      100893   169         18         Pass
2387      100893   170          6         Pass
2388      100893   171         32         Pass
2389      100893   187         15         Pass
2390      100893   201          4         Pass
2391      100893   205          4         Pass
2392      100893   206         11         Pass
2393      100893   207         14         Pass
2394      100893   208          3         Pass
2395      100893   209          2         Pass
2396      100893   216         20         Pass
2397      100893   217         26         Pass
2398      100893   218          7         Pass
2399      100893   228         71         Pass
2400      100893   231          1         Pass
2401      100893   242          2         Pass
2402      100893   243         30         Pass
2403      100893   250         17         Pass

# METRICS (LACE)

In [14]:
feature_names=('Pass','Fail', 'Distinction', 'Withdrawn')
with open("studentTree.dot", 'w') as f:
         f = tree.export_graphviz(clf, out_file=f, feature_names=feature_names)

ValueError: Length of feature_names, 4 does not match number of features, 1

In [ ]:
plt.hist(testArr)

In [ ]:
plt.hist(testArr, density=True,color='indianred',alpha=0.5,bins=20)
#plt.hist(output, normed=True,alpha=0.5,bins=20)

In [ ]:
sns.distplot(testArr,bins=25,
            kde_kws={'color':'indianred','label':'KDE PLOT'},
            hist_kws={'color':'blue','label':"HIST"})

In [ ]:
plt.hist(testArr, density=True,color='indianred',alpha=0.5,bins=20)
plt.hist(trainArr, density=True,alpha=0.5,bins=20)

In [ ]:
sns.heatmap(testArr)